-- Eliminar tablas si existen
DROP TABLE IF EXISTS consumo CASCADE;
DROP TABLE IF EXISTS direccion CASCADE;
DROP TABLE IF EXISTS divisa CASCADE;
DROP TABLE IF EXISTS estadia CASCADE;
DROP TABLE IF EXISTS estado_habitacion CASCADE;
DROP TABLE IF EXISTS factura CASCADE;
DROP TABLE IF EXISTS habitacion CASCADE;
DROP TABLE IF EXISTS huesped CASCADE;
DROP TABLE IF EXISTS nota_de_credito CASCADE;
DROP TABLE IF EXISTS pago CASCADE;
DROP TABLE IF EXISTS persona CASCADE;
DROP TABLE IF EXISTS reserva CASCADE;
DROP TABLE IF EXISTS reserva_habitacion CASCADE;
DROP TABLE IF EXISTS reserva_lista_habitaciones_rerservadas CASCADE;
DROP TABLE IF EXISTS responsable_de_pago CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

-- Tabla consumo
CREATE TABLE consumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor DOUBLE PRECISION NOT NULL,
    estadia_id BIGINT,
    dtype VARCHAR(31) NOT NULL,
    descripcion VARCHAR(255),
    estado VARCHAR(255),
    tipo VARCHAR(255),
    CONSTRAINT fk_consumo_estadia FOREIGN KEY (estadia_id) REFERENCES estadia(id)
);

-- Tabla direccion
CREATE TABLE direccion (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_postal INT,
    numero INT NOT NULL,
    piso INT NOT NULL,
    calle VARCHAR(255),
    departamento VARCHAR(255),
    localidad VARCHAR(255),
    pais VARCHAR(255),
    provincia VARCHAR(255)
);

-- Tabla divisa
CREATE TABLE divisa (
    tipo VARCHAR(255) PRIMARY KEY,
    cotizacion DOUBLE PRECISION NOT NULL
);

-- Tabla estadia
CREATE TABLE estadia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_check_in DATE,
    fecha_check_out TIMESTAMP,
    valor_estadia REAL,
    habitacion_id BIGINT NOT NULL,
    CONSTRAINT fk_estadia_habitacion FOREIGN KEY (habitacion_id) REFERENCES habitacion(numero_habitacion)
);

-- Tabla estado_habitacion
CREATE TABLE estado_habitacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado SMALLINT CHECK (estado >= 0 AND estado <= 3),
    fecha_inicio DATE,
    fecha_fin DATE,
    habitacion_id BIGINT,
    CONSTRAINT fk_estado_habitacion FOREIGN KEY (habitacion_id) REFERENCES habitacion(numero_habitacion)
);

-- Tabla factura
CREATE TABLE factura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total DOUBLE PRECISION NOT NULL,
    estadia_id BIGINT,
    nota_de_credito_id BIGINT,
    responsable_de_pago_id BIGINT,
    estado VARCHAR(255),
    tipo_factura VARCHAR(255),
    CONSTRAINT fk_factura_estadia FOREIGN KEY (estadia_id) REFERENCES estadia(id),
    CONSTRAINT fk_factura_nota FOREIGN KEY (nota_de_credito_id) REFERENCES nota_de_credito(numero_nota),
    CONSTRAINT fk_factura_responsable FOREIGN KEY (responsable_de_pago_id) REFERENCES responsable_de_pago(id),
    CONSTRAINT factura_responsable_de_pago_id_key UNIQUE (responsable_de_pago_id)
);

-- Tabla habitacion
CREATE TABLE habitacion (
    numero_habitacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_camad INT NOT NULL,
    cantidad_camai INT NOT NULL,
    cantidad_camaks INT NOT NULL,
    cantidad_huespedes INT NOT NULL,
    tipo VARCHAR(255)
);

-- Tabla huesped
CREATE TABLE huesped (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estadia_id BIGINT,
    condicioniva VARCHAR(255) NOT NULL CHECK (condicioniva IN ('RESPONSABLE_INSCRIPTO','MONOTRIBUTO','CONSUMIDOR_FINAL','EXENTO')),
    email VARCHAR(255),
    ocupacion VARCHAR(255) NOT NULL,
    telefono VARCHAR(255) NOT NULL,
    CONSTRAINT fk_huesped_estadia FOREIGN KEY (estadia_id) REFERENCES estadia(id),
    CONSTRAINT fk_huesped_persona FOREIGN KEY (id) REFERENCES persona(id)
);

-- Tabla nota_de_credito
CREATE TABLE nota_de_credito (
    numero_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    importe_neto DOUBLE PRECISION NOT NULL,
    importe_total DOUBLE PRECISION NOT NULL,
    iva DOUBLE PRECISION NOT NULL,
    responsable_de_pago_id BIGINT,
    CONSTRAINT fk_nota_responsable FOREIGN KEY (responsable_de_pago_id) REFERENCES responsable_de_pago(id),
    CONSTRAINT nota_de_credito_responsable_de_pago_id_key UNIQUE (responsable_de_pago_id)
);

-- Tabla pago
CREATE TABLE pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_cobro DATE,
    fecha_pago DATE,
    fecha_vencimiento DATE,
    monto DOUBLE PRECISION NOT NULL,
    monto_de_pago DOUBLE PRECISION,
    numero_tarjeta INT,
    factura_id BIGINT,
    numero_cheque BIGINT,
    dtype VARCHAR(31) NOT NULL,
    banco_emisor VARCHAR(255),
    divisa_tipo VARCHAR(255),
    estado VARCHAR(255),
    nombre_titular VARCHAR(255),
    red_de_pago VARCHAR(255),
    tipo VARCHAR(255),
    CONSTRAINT fk_pago_factura FOREIGN KEY (factura_id) REFERENCES factura(id),
    CONSTRAINT fk_pago_divisa FOREIGN KEY (divisa_tipo) REFERENCES divisa(tipo)
);

-- Tabla persona
CREATE TABLE persona (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direccion_id INT UNIQUE,
    fecha_nacimiento DATE,
    tipo_documento SMALLINT CHECK (tipo_documento >= 0 AND tipo_documento <= 4),
    cuit BIGINT NOT NULL,
    num_documento BIGINT NOT NULL,
    apellido VARCHAR(255),
    nacionalidad VARCHAR(255),
    nombre VARCHAR(255),
    CONSTRAINT fk_persona_direccion FOREIGN KEY (direccion_id) REFERENCES direccion(id)
);

-- Tabla reserva
CREATE TABLE reserva (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    huesped_id BIGINT NOT NULL,
    CONSTRAINT fk_reserva_huesped FOREIGN KEY (huesped_id) REFERENCES huesped(id)
);

-- Tabla reserva_habitacion
CREATE TABLE reserva_habitacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva INT,
    habitacion_fk BIGINT NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE,
    CONSTRAINT fk_reserva_habitacion_reserva FOREIGN KEY (id_reserva) REFERENCES reserva(id),
    CONSTRAINT fk_reserva_habitacion_habitacion FOREIGN KEY (habitacion_fk) REFERENCES habitacion(numero_habitacion)
);

-- Tabla reserva_lista_habitaciones_rerservadas
CREATE TABLE reserva_lista_habitaciones_rerservadas (
    reserva_id INT NOT NULL,
    lista_habitaciones_rerservadas_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_reserva_lista_reserva FOREIGN KEY (reserva_id) REFERENCES reserva(id),
    CONSTRAINT fk_reserva_lista_habitacion FOREIGN KEY (lista_habitaciones_rerservadas_id) REFERENCES reserva_habitacion(id)
);

-- Tabla responsable_de_pago
CREATE TABLE responsable_de_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razon_social VARCHAR(255),
    condicioniva SMALLINT CHECK (condicioniva >= 0 AND condicioniva <= 3),
    CONSTRAINT fk_responsable_persona FOREIGN KEY (id) REFERENCES persona(id)
);

-- Tabla usuario
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);