--
-- PostgreSQL database dump
--

\restrict fgjF1QJmHzvRWYDUcwsAPRC2csJEVE3cwWkbJQ0BXhGUGVa99TEosgaOWtAq47K

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2025-12-02 17:01:32

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5131 (class 1262 OID 16629)
-- Name: desarrollo; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE desarrollo WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Spain.1252';


\unrestrict fgjF1QJmHzvRWYDUcwsAPRC2csJEVE3cwWkbJQ0BXhGUGVa99TEosgaOWtAq47K
\connect desarrollo
\restrict fgjF1QJmHzvRWYDUcwsAPRC2csJEVE3cwWkbJQ0BXhGUGVa99TEosgaOWtAq47K

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 220 (class 1259 OID 16631)
-- Name: consumo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consumo (
    dtype character varying(31) NOT NULL,
    id bigint NOT NULL,
    estado character varying(255),
    tipo character varying(255),
    valor double precision NOT NULL,
    descripcion character varying(255),
    estadia_id bigint
);


--
-- TOC entry 219 (class 1259 OID 16630)
-- Name: consumo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.consumo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consumo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16642)
-- Name: direccion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.direccion (
    id integer NOT NULL,
    calle character varying(255),
    codigo_postal integer,
    departamento character varying(255),
    localidad character varying(255),
    numero integer NOT NULL,
    pais character varying(255),
    piso integer NOT NULL,
    provincia character varying(255)
);


--
-- TOC entry 221 (class 1259 OID 16641)
-- Name: direccion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.direccion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.direccion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16652)
-- Name: divisa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.divisa (
    tipo character varying(255) NOT NULL,
    cotizacion double precision NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 16660)
-- Name: estadia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estadia (
    id bigint NOT NULL,
    fecha_check_in date,
    fecha_check_out date,
    valor_estadia real,
    habitacion_id bigint NOT NULL
);


--
-- TOC entry 224 (class 1259 OID 16659)
-- Name: estadia_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estadia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estadia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16668)
-- Name: estado_habitacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estado_habitacion (
    id bigint NOT NULL,
    estado smallint,
    fecha_fin date,
    fecha_inicio date,
    habitacion_id bigint,
    CONSTRAINT estado_habitacion_estado_check CHECK (((estado >= 0) AND (estado <= 3)))
);


--
-- TOC entry 226 (class 1259 OID 16667)
-- Name: estado_habitacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estado_habitacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estado_habitacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16676)
-- Name: factura; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.factura (
    id bigint NOT NULL,
    estado character varying(255),
    tipo_factura character varying(255),
    total double precision NOT NULL,
    responsable_de_pago_id bigint,
    nota_de_credito_id bigint,
    estadia_id bigint
);


--
-- TOC entry 228 (class 1259 OID 16675)
-- Name: factura_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.factura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.factura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16686)
-- Name: habitacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.habitacion (
    numero_habitacion bigint NOT NULL,
    cantidad_camad integer NOT NULL,
    cantidad_camai integer NOT NULL,
    cantidad_camaks integer NOT NULL,
    cantidad_huespedes integer NOT NULL,
    tipo character varying(255)
);


--
-- TOC entry 230 (class 1259 OID 16685)
-- Name: habitacion_numero_habitacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.habitacion ALTER COLUMN numero_habitacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.habitacion_numero_habitacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16696)
-- Name: huesped; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.huesped (
    condicioniva character varying(255) NOT NULL,
    email character varying(255),
    ocupacion character varying(255) NOT NULL,
    telefono character varying(255) NOT NULL,
    id bigint NOT NULL,
    estadia_id bigint,
    CONSTRAINT huesped_condicioniva_check CHECK (((condicioniva)::text = ANY ((ARRAY['RESPONSABLE_INSCRIPTO'::character varying, 'MONOTRIBUTO'::character varying, 'CONSUMIDOR_FINAL'::character varying, 'EXENTO'::character varying])::text[])))
);


--
-- TOC entry 234 (class 1259 OID 16709)
-- Name: nota_de_credito; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nota_de_credito (
    numero_nota bigint NOT NULL,
    importe_neto double precision NOT NULL,
    importe_total double precision NOT NULL,
    iva double precision NOT NULL,
    responsable_de_pago_id bigint
);


--
-- TOC entry 233 (class 1259 OID 16708)
-- Name: nota_de_credito_numero_nota_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nota_de_credito ALTER COLUMN numero_nota ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nota_de_credito_numero_nota_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16719)
-- Name: pago; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pago (
    dtype character varying(31) NOT NULL,
    id bigint NOT NULL,
    estado character varying(255),
    fecha_pago date,
    monto double precision NOT NULL,
    banco_emisor character varying(255),
    fecha_cobro date,
    numero_cheque bigint,
    tipo character varying(255),
    monto_de_pago double precision,
    fecha_vencimiento date,
    nombre_titular character varying(255),
    numero_tarjeta integer,
    red_de_pago character varying(255),
    divisa_tipo character varying(255),
    factura_id bigint
);


--
-- TOC entry 235 (class 1259 OID 16718)
-- Name: pago_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16730)
-- Name: persona; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persona (
    id bigint NOT NULL,
    apellido character varying(255),
    cuit bigint NOT NULL,
    fecha_nacimiento date,
    nacionalidad character varying(255),
    nombre character varying(255),
    num_documento bigint NOT NULL,
    tipo_documento smallint,
    direccion_id integer,
    CONSTRAINT persona_tipo_documento_check CHECK (((tipo_documento >= 0) AND (tipo_documento <= 4)))
);


--
-- TOC entry 237 (class 1259 OID 16729)
-- Name: persona_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.persona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16742)
-- Name: reserva; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reserva (
    id integer NOT NULL,
    huesped_id bigint NOT NULL
);


--
-- TOC entry 243 (class 1259 OID 16755)
-- Name: reserva_habitacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reserva_habitacion (
    id bigint NOT NULL,
    fecha_fin date,
    fecha_inicio date,
    habitacion_fk bigint NOT NULL,
    id_reserva integer
);


--
-- TOC entry 242 (class 1259 OID 16754)
-- Name: reserva_habitacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reserva_habitacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reserva_habitacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16741)
-- Name: reserva_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reserva ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reserva_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16749)
-- Name: reserva_lista_habitaciones_rerservadas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reserva_lista_habitaciones_rerservadas (
    reserva_id integer NOT NULL,
    lista_habitaciones_rerservadas_id bigint CONSTRAINT reserva_lista_habitaciones__lista_habitaciones_rerserv_not_null NOT NULL
);


--
-- TOC entry 244 (class 1259 OID 16762)
-- Name: responsable_de_pago; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.responsable_de_pago (
    razon_social character varying(255),
    id bigint NOT NULL
);


--
-- TOC entry 4926 (class 2606 OID 16640)
-- Name: consumo consumo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consumo
    ADD CONSTRAINT consumo_pkey PRIMARY KEY (id);


--
-- TOC entry 4928 (class 2606 OID 16651)
-- Name: direccion direccion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_pkey PRIMARY KEY (id);


--
-- TOC entry 4930 (class 2606 OID 16658)
-- Name: divisa divisa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.divisa
    ADD CONSTRAINT divisa_pkey PRIMARY KEY (tipo);


--
-- TOC entry 4932 (class 2606 OID 16666)
-- Name: estadia estadia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estadia
    ADD CONSTRAINT estadia_pkey PRIMARY KEY (id);


--
-- TOC entry 4934 (class 2606 OID 16674)
-- Name: estado_habitacion estado_habitacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estado_habitacion
    ADD CONSTRAINT estado_habitacion_pkey PRIMARY KEY (id);


--
-- TOC entry 4936 (class 2606 OID 16684)
-- Name: factura factura_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT factura_pkey PRIMARY KEY (id);


--
-- TOC entry 4940 (class 2606 OID 16695)
-- Name: habitacion habitacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.habitacion
    ADD CONSTRAINT habitacion_pkey PRIMARY KEY (numero_habitacion);


--
-- TOC entry 4942 (class 2606 OID 16707)
-- Name: huesped huesped_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.huesped
    ADD CONSTRAINT huesped_pkey PRIMARY KEY (id);


--
-- TOC entry 4944 (class 2606 OID 16717)
-- Name: nota_de_credito nota_de_credito_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota_de_credito
    ADD CONSTRAINT nota_de_credito_pkey PRIMARY KEY (numero_nota);


--
-- TOC entry 4948 (class 2606 OID 16728)
-- Name: pago pago_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT pago_pkey PRIMARY KEY (id);


--
-- TOC entry 4950 (class 2606 OID 16740)
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (id);


--
-- TOC entry 4958 (class 2606 OID 16761)
-- Name: reserva_habitacion reserva_habitacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reserva_habitacion
    ADD CONSTRAINT reserva_habitacion_pkey PRIMARY KEY (id);


--
-- TOC entry 4954 (class 2606 OID 16748)
-- Name: reserva reserva_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reserva
    ADD CONSTRAINT reserva_pkey PRIMARY KEY (id);


--
-- TOC entry 4960 (class 2606 OID 16767)
-- Name: responsable_de_pago responsable_de_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.responsable_de_pago
    ADD CONSTRAINT responsable_de_pago_pkey PRIMARY KEY (id);


--
-- TOC entry 4952 (class 2606 OID 16773)
-- Name: persona uk5r4ylkylsvg36w6r55caym9vw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT uk5r4ylkylsvg36w6r55caym9vw UNIQUE (direccion_id);


--
-- TOC entry 4956 (class 2606 OID 16775)
-- Name: reserva_lista_habitaciones_rerservadas uk7lh4y1n09vcxkhg4bjb7888u9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reserva_lista_habitaciones_rerservadas
    ADD CONSTRAINT uk7lh4y1n09vcxkhg4bjb7888u9 UNIQUE (lista_habitaciones_rerservadas_id);


--
-- TOC entry 4946 (class 2606 OID 16771)
-- Name: nota_de_credito uk96h2gmxfkx2sewvu1s7lv3ljc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota_de_credito
    ADD CONSTRAINT uk96h2gmxfkx2sewvu1s7lv3ljc UNIQUE (responsable_de_pago_id);


--
-- TOC entry 4938 (class 2606 OID 16769)
-- Name: factura ukjt0fbtvm6iigolligj95vdlsn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT ukjt0fbtvm6iigolligj95vdlsn UNIQUE (responsable_de_pago_id);


--
-- TOC entry 4974 (class 2606 OID 16846)
-- Name: reserva_lista_habitaciones_rerservadas fk4dfulbbf6ndcinxr4rtrce06a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reserva_lista_habitaciones_rerservadas
    ADD CONSTRAINT fk4dfulbbf6ndcinxr4rtrce06a FOREIGN KEY (reserva_id) REFERENCES public.reserva(id);


--
-- TOC entry 4976 (class 2606 OID 16851)
-- Name: reserva_habitacion fk5ju6jrrhfct1q0svajgju8p2p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reserva_habitacion
    ADD CONSTRAINT fk5ju6jrrhfct1q0svajgju8p2p FOREIGN KEY (habitacion_fk) REFERENCES public.habitacion(numero_habitacion);


--
-- TOC entry 4970 (class 2606 OID 16821)
-- Name: pago fk74mwwklvt43hvgnd2n6q403c0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT fk74mwwklvt43hvgnd2n6q403c0 FOREIGN KEY (divisa_tipo) REFERENCES public.divisa(tipo);


--
-- TOC entry 4972 (class 2606 OID 16831)
-- Name: persona fk78198ggd6thip6qloht9ho248; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT fk78198ggd6thip6qloht9ho248 FOREIGN KEY (direccion_id) REFERENCES public.direccion(id);


--
-- TOC entry 4964 (class 2606 OID 16801)
-- Name: factura fk7vyk8uhc1mg335pl8gs88au0i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fk7vyk8uhc1mg335pl8gs88au0i FOREIGN KEY (estadia_id) REFERENCES public.estadia(id);


--
-- TOC entry 4961 (class 2606 OID 16776)
-- Name: consumo fk8wqbhvh22aj2qs695yf1sak2h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consumo
    ADD CONSTRAINT fk8wqbhvh22aj2qs695yf1sak2h FOREIGN KEY (estadia_id) REFERENCES public.estadia(id);


--
-- TOC entry 4975 (class 2606 OID 16841)
-- Name: reserva_lista_habitaciones_rerservadas fk9pcvq5wr1vc1oed58obin53j1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reserva_lista_habitaciones_rerservadas
    ADD CONSTRAINT fk9pcvq5wr1vc1oed58obin53j1 FOREIGN KEY (lista_habitaciones_rerservadas_id) REFERENCES public.reserva_habitacion(id);


--
-- TOC entry 4978 (class 2606 OID 16861)
-- Name: responsable_de_pago fkaneaocapooc4y7v4nl0tm5tbh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.responsable_de_pago
    ADD CONSTRAINT fkaneaocapooc4y7v4nl0tm5tbh FOREIGN KEY (id) REFERENCES public.persona(id);


--
-- TOC entry 4965 (class 2606 OID 16796)
-- Name: factura fkbexvbdxbrk9sxmcy8ops6vvet; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fkbexvbdxbrk9sxmcy8ops6vvet FOREIGN KEY (nota_de_credito_id) REFERENCES public.nota_de_credito(numero_nota);


--
-- TOC entry 4973 (class 2606 OID 16836)
-- Name: reserva fkbko6p7864ytkn1ul5b78cyb9g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reserva
    ADD CONSTRAINT fkbko6p7864ytkn1ul5b78cyb9g FOREIGN KEY (huesped_id) REFERENCES public.huesped(id);


--
-- TOC entry 4969 (class 2606 OID 16816)
-- Name: nota_de_credito fkc19tif3qy02k9258sxc8yebak; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota_de_credito
    ADD CONSTRAINT fkc19tif3qy02k9258sxc8yebak FOREIGN KEY (responsable_de_pago_id) REFERENCES public.responsable_de_pago(id);


--
-- TOC entry 4966 (class 2606 OID 16791)
-- Name: factura fki6mvuvdecewfcjeu4e2asmru4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fki6mvuvdecewfcjeu4e2asmru4 FOREIGN KEY (responsable_de_pago_id) REFERENCES public.responsable_de_pago(id);


--
-- TOC entry 4962 (class 2606 OID 16781)
-- Name: estadia fkjamwmx6nn22q6uiwmdfroh1pm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estadia
    ADD CONSTRAINT fkjamwmx6nn22q6uiwmdfroh1pm FOREIGN KEY (habitacion_id) REFERENCES public.habitacion(numero_habitacion);


--
-- TOC entry 4967 (class 2606 OID 16806)
-- Name: huesped fkmjnoli7qv55nwiy8y0h1k7tho; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.huesped
    ADD CONSTRAINT fkmjnoli7qv55nwiy8y0h1k7tho FOREIGN KEY (id) REFERENCES public.persona(id);


--
-- TOC entry 4977 (class 2606 OID 16856)
-- Name: reserva_habitacion fko207eenehqpc4e26xcl0ahecp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reserva_habitacion
    ADD CONSTRAINT fko207eenehqpc4e26xcl0ahecp FOREIGN KEY (id_reserva) REFERENCES public.reserva(id);


--
-- TOC entry 4963 (class 2606 OID 16786)
-- Name: estado_habitacion fkrrhe4x95dnmbpexmkrg8hd4d6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estado_habitacion
    ADD CONSTRAINT fkrrhe4x95dnmbpexmkrg8hd4d6 FOREIGN KEY (habitacion_id) REFERENCES public.habitacion(numero_habitacion);


--
-- TOC entry 4971 (class 2606 OID 16826)
-- Name: pago fkrtu0je6xnvrvwuflslyslq2eo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT fkrtu0je6xnvrvwuflslyslq2eo FOREIGN KEY (factura_id) REFERENCES public.factura(id);


--
-- TOC entry 4968 (class 2606 OID 16811)
-- Name: huesped fktdfx9kw56xshx79ctlwl6kksm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.huesped
    ADD CONSTRAINT fktdfx9kw56xshx79ctlwl6kksm FOREIGN KEY (estadia_id) REFERENCES public.estadia(id);


-- Completed on 2025-12-02 17:01:32

--
-- PostgreSQL database dump complete
--

\unrestrict fgjF1QJmHzvRWYDUcwsAPRC2csJEVE3cwWkbJQ0BXhGUGVa99TEosgaOWtAq47K

