-- Eliminar tablas si existen
DROP TABLE IF EXISTS consumo CASCADE;
DROP TABLE IF EXISTS direccion CASCADE;
DROP TABLE IF EXISTS divisa CASCADE;
DROP TABLE IF EXISTS estadia CASCADE;
DROP TABLE IF EXISTS estado_habitacion CASCADE;
DROP TABLE IF EXISTS factura CASCADE;
DROP TABLE IF EXISTS habitacion CASCADE;
DROP TABLE IF EXISTS huesped CASCADE;
DROP TABLE IF EXISTS nota_de_credito CASCADE;
DROP TABLE IF EXISTS pago CASCADE;
DROP TABLE IF EXISTS persona CASCADE;
DROP TABLE IF EXISTS reserva CASCADE;
DROP TABLE IF EXISTS reserva_habitacion CASCADE;
DROP TABLE IF EXISTS reserva_lista_habitaciones_rerservadas CASCADE;
DROP TABLE IF EXISTS responsable_de_pago CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

-- Crear tablas sin constraints
CREATE TABLE consumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    valor DOUBLE PRECISION NOT NULL,
    estadia_id BIGINT,
    dtype VARCHAR(31) NOT NULL,
    descripcion VARCHAR(255),
    estado VARCHAR(255),
    tipo VARCHAR(255)
);

CREATE TABLE direccion (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    codigo_postal INT,
    numero INT NOT NULL,
    piso INT NOT NULL,
    calle VARCHAR(255),
    departamento VARCHAR(255),
    localidad VARCHAR(255),
    pais VARCHAR(255),
    provincia VARCHAR(255)
);

CREATE TABLE divisa (
    tipo VARCHAR(255),
    cotizacion DOUBLE PRECISION NOT NULL
);

CREATE TABLE estadia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha_check_in DATE,
    fecha_check_out TIMESTAMP,
    valor_estadia REAL,
    habitacion_id BIGINT NOT NULL
);

CREATE TABLE estado_habitacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    estado SMALLINT,
    fecha_inicio DATE,
    fecha_fin DATE,
    habitacion_id BIGINT
);

CREATE TABLE factura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    total DOUBLE PRECISION NOT NULL,
    estadia_id BIGINT,
    nota_de_credito_id BIGINT,
    responsable_de_pago_id BIGINT,
    estado VARCHAR(255),
    tipo_factura VARCHAR(255)
);

CREATE TABLE habitacion (
    numero_habitacion BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cantidad_camad INT NOT NULL,
    cantidad_camai INT NOT NULL,
    cantidad_camaks INT NOT NULL,
    cantidad_huespedes INT NOT NULL,
    tipo VARCHAR(255)
);

CREATE TABLE huesped (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    estadia_id BIGINT,
    condicioniva VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    ocupacion VARCHAR(255) NOT NULL,
    telefono VARCHAR(255) NOT NULL
);

CREATE TABLE nota_de_credito (
    numero_nota BIGINT GENERATED BY DEFAULT AS IDENTITY,
    importe_neto DOUBLE PRECISION NOT NULL,
    importe_total DOUBLE PRECISION NOT NULL,
    iva DOUBLE PRECISION NOT NULL,
    responsable_de_pago_id BIGINT
);

CREATE TABLE pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha_cobro DATE,
    fecha_pago DATE,
    fecha_vencimiento DATE,
    monto DOUBLE PRECISION NOT NULL,
    monto_de_pago DOUBLE PRECISION,
    numero_tarjeta INT,
    factura_id BIGINT,
    numero_cheque BIGINT,
    dtype VARCHAR(31) NOT NULL,
    banco_emisor VARCHAR(255),
    divisa_tipo VARCHAR(255),
    estado VARCHAR(255),
    nombre_titular VARCHAR(255),
    red_de_pago VARCHAR(255),
    tipo VARCHAR(255)
);

CREATE TABLE persona (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    direccion_id INT,
    fecha_nacimiento DATE,
    tipo_documento SMALLINT,
    cuit BIGINT NOT NULL,
    num_documento BIGINT NOT NULL,
    apellido VARCHAR(255),
    nacionalidad VARCHAR(255),
    nombre VARCHAR(255)
);

CREATE TABLE reserva (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    huesped_id BIGINT NOT NULL
);

CREATE TABLE reserva_habitacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_reserva INT,
    habitacion_fk BIGINT NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE
);

CREATE TABLE reserva_lista_habitaciones_rerservadas (
    reserva_id INT NOT NULL,
    lista_habitaciones_rerservadas_id BIGINT NOT NULL
);

CREATE TABLE responsable_de_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    razon_social VARCHAR(255),
    condicioniva SMALLINT
);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);

-- =========================
-- Constraints (PK, FK, UK)
-- =========================

-- Primary Keys
ALTER TABLE consumo ADD CONSTRAINT consumo_pkey PRIMARY KEY (id);
ALTER TABLE direccion ADD CONSTRAINT direccion_pkey PRIMARY KEY (id);
ALTER TABLE divisa ADD CONSTRAINT divisa_pkey PRIMARY KEY (tipo);
ALTER TABLE estadia ADD CONSTRAINT estadia_pkey PRIMARY KEY (id);
ALTER TABLE estado_habitacion ADD CONSTRAINT estado_habitacion_pkey PRIMARY KEY (id);
ALTER TABLE factura ADD CONSTRAINT factura_pkey PRIMARY KEY (id);
ALTER TABLE habitacion ADD CONSTRAINT habitacion_pkey PRIMARY KEY (numero_habitacion);
ALTER TABLE huesped ADD CONSTRAINT huesped_pkey PRIMARY KEY (id);
ALTER TABLE nota_de_credito ADD CONSTRAINT nota_de_credito_pkey PRIMARY KEY (numero_nota);
ALTER TABLE pago ADD CONSTRAINT pago_pkey PRIMARY KEY (id);
ALTER TABLE persona ADD CONSTRAINT persona_pkey PRIMARY KEY (id);
ALTER TABLE reserva ADD CONSTRAINT reserva_pkey PRIMARY KEY (id);
ALTER TABLE reserva_habitacion ADD CONSTRAINT reserva_habitacion_pkey PRIMARY KEY (id);
ALTER TABLE responsable_de_pago ADD CONSTRAINT responsable_de_pago_pkey PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);

-- Unique constraints
ALTER TABLE factura ADD CONSTRAINT factura_responsable_de_pago_id_key UNIQUE (responsable_de_pago_id);
ALTER TABLE nota_de_credito ADD CONSTRAINT nota_de_credito_responsable_de_pago_id_key UNIQUE (responsable_de_pago_id);
ALTER TABLE persona ADD CONSTRAINT persona_direccion_id_key UNIQUE (direccion_id);
ALTER TABLE reserva_lista_habitaciones_rerservadas ADD CONSTRAINT reserva_lista_habitaciones_rerservadas_id_key UNIQUE (lista_habitaciones_rerservadas_id);
ALTER TABLE usuario ADD CONSTRAINT usuario_username_key UNIQUE (username);

-- Foreign Keys
ALTER TABLE consumo ADD CONSTRAINT fk_consumo_estadia FOREIGN KEY (estadia_id) REFERENCES estadia(id);
ALTER TABLE estadia ADD CONSTRAINT fk_estadia_habitacion FOREIGN KEY (habitacion_id) REFERENCES habitacion(numero_habitacion);
ALTER TABLE estado_habitacion ADD CONSTRAINT fk_estado_habitacion FOREIGN KEY (habitacion_id) REFERENCES habitacion(numero_habitacion);
ALTER TABLE factura ADD CONSTRAINT fk_factura_estadia FOREIGN KEY (estadia_id) REFERENCES estadia(id);
ALTER TABLE factura ADD CONSTRAINT fk_factura_nota FOREIGN KEY (nota_de_credito_id) REFERENCES nota_de_credito(numero_nota);
ALTER TABLE factura ADD CONSTRAINT fk_factura_responsable FOREIGN KEY (responsable_de_pago_id) REFERENCES responsable_de_pago(id);
ALTER TABLE huesped ADD CONSTRAINT fk_huesped_estadia FOREIGN KEY (estadia_id) REFERENCES estadia(id);
ALTER TABLE huesped ADD CONSTRAINT fk_huesped_persona FOREIGN KEY (id) REFERENCES persona(id);
ALTER TABLE nota_de_credito ADD CONSTRAINT fk_nota_responsable FOREIGN KEY (responsable_de_pago_id) REFERENCES responsable_de_pago(id);
ALTER TABLE pago ADD CONSTRAINT fk_pago_factura FOREIGN KEY (factura_id) REFERENCES factura(id);
ALTER TABLE pago ADD CONSTRAINT fk_pago_divisa FOREIGN KEY (divisa_tipo) REFERENCES divisa(tipo);
ALTER TABLE persona ADD CONSTRAINT fk_persona_direccion FOREIGN KEY (direccion_id) REFERENCES direccion(id);
ALTER TABLE reserva ADD CONSTRAINT fk_reserva_huesped FOREIGN KEY (huesped_id) REFERENCES huesped(id);
ALTER TABLE reserva_habitacion ADD CONSTRAINT fk_reserva_habitacion_reserva FOREIGN KEY (id_reserva) REFERENCES reserva(id);
ALTER TABLE reserva_habitacion ADD CONSTRAINT fk_reserva_habitacion_habitacion FOREIGN KEY (habitacion_fk) REFERENCES habitacion(numero_habitacion);
ALTER TABLE reserva_lista_habitaciones_rerservadas ADD CONSTRAINT fk_reserva_lista_reserva FOREIGN KEY (reserva_id) REFERENCES reserva(id);
ALTER TABLE reserva_lista_habitaciones_rerservadas ADD CONSTRAINT fk_reserva_lista_habitacion FOREIGN KEY (lista_habitaciones_rerservadas_id) REFERENCES reserva_habitacion(id);
ALTER TABLE responsable_de_pago ADD CONSTRAINT fk_responsable_persona FOREIGN KEY (id) REFERENCES persona(id);